### ISSUE TITLE
Add  lower() to class DecimalCollection

### ISSUE THREAD

**Issue by rrocamar** [rrocamar/IWVG.SwC.RamonRoca#3]
Devoler el número menor de una colección de números reales.
[Ver en la wiki.](https://github.com/rrocamar/IWVG.SwC.RamonRoca/wiki/Clase-DecimalCollection#public-double-lower)

**Comment by manupuchades** [comment]
El lunes por la tarde/noche estará lista

**Comment by manupuchades** [comment]
Desarrollo + Test finalizados
