### ISSUE TITLE
Add multiply(Fraction fraction) to Class Fraction

### ISSUE THREAD

**Issue by rrocamar** [rrocamar/IWVG.SwC.RamonRoca#5]
Calcula el resultado de multiplicar dos fracciones.
[Ver en la wiki.](https://github.com/rrocamar/IWVG.SwC.RamonRoca/wiki/Clase-Fraction#public-fraction-multiplyfraction-fraction)

**Comment by manupuchades** [comment]
El lunes por la tarde/noche estará lista

**Comment by manupuchades** [comment]
Desarrollo + Test finalizados
